# use to create a swarm template in Portainer
# STACK_BASE_PATH [base folder where to host files, must exists]
# STACK_BASE_PATH=/srv/data/docker/containers/failover ; grep device failover-stack-4-swarm.yml|grep -v "#"|awk '{print $2}'|while read dir; do eval mkdir -p $dir; done

version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      #max_attempts: 3
      window: 20s
  
services:
  db:
    image: mariadb:10
    hostname: db
    <<: *default-opts    
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /var/lib/mysql/db-root.pwd
      MYSQL_PASSWORD_FILE: /var/lib/mysql/db-password.pwd
      MYSQL_DATABASE_FILE: /var/lib/mysql/db-name.txt
      MYSQL_USER_FILE: /var/lib/mysql/db-user.txt
      TZ: Europe/Rome
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "read p < $$MYSQL_PASSWORD_FILE ; read u < $$MYSQL_USER_FILE ; mysql -p$$p -u$$u -e status | grep Uptime || (echo \"MariaDB is down\" && exit 1)"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    <<: *default-opts
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8380:80'
    depends_on:
      - db

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/docker/containers/failover/db
