# use to create a swarm template in Portainer
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 20s

x-environment: &common-vars
    TZ: Europe/Rome

services:
  redis:
    image: redis:5-alpine
    hostname: redis-honey
    <<: *default-opts    
    environment:
      << : *common-vars
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_db:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    # according to https://github.com/moby/moby/pull/37701#issuecomment-448014841
    # on docker 19.03 you will be able to set /proc/sys/net/core/somaxconn to 511 instead of default 128
    # like this example below (maybe syntax will change)
    #sysctls:
    #  - net.core.somaxconn=511
    stop_grace_period: 1m

  rspamd:
    image: neomediatech/rspamd-honey:latest
    hostname: rspamd-honey
    <<: *default-opts
    ports:
      - target: 11334
        published: 11334
        protocol: tcp
        mode: host
    volumes:
      - rspamd_data:/var/lib/rspamd
      - logs:/var/log/rspamd/
    environment:
      << : *common-vars
      WAITFOR: clamav:clamav
    depends_on:
      - redis
      - clamav
    stop_grace_period: 1m

  dcc:
    image: neomediatech/dcc:latest
    hostname: dcc-honey
    <<: *default-opts    
    environment:
      << : *common-vars

  nginx:
    image: nginx:1.17-alpine
    hostname: nginx-honey
    <<: *default-opts
    ports:
      - target: 80
        published: 81
        protocol: tcp
        mode: host    
    volumes:
      - web:/usr/share/nginx/html/
      - nginx_confs:/etc/nginx/conf.d/
      - logs:/logs/
    environment:
      << : *common-vars
    depends_on:
      - php-fpm
    command: ["nginx", "-g", "daemon off;"]
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "nc -w 7 -zv 0.0.0.0 80 || (echo \"Very bad things are happening here...\" && exit 1)"]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 6

  exim:
    image: neomediatech/exim-honey-alpine:latest
    hostname: exim-honey
    <<: *default-opts    
    ports:
      - target: 25
        published: 1025
        protocol: tcp
        mode: host
      - target: 465
        published: 10465
        protocol: tcp
        mode: host
      - target: 587
        published: 10587
        protocol: tcp
        mode: host
    volumes:
      - logs:/var/log/exim/
      - exim_good_data:/data/mail
    environment:
      << : *common-vars
      WAITFOR: "dovecot:dovecot clamav:clamav redis:redis rspamd:rspamd"
    depends_on:
      - dovecot
      - clamav
      - redis
      - rspamd

  clamav:
    image: neomediatech/clamav:latest
    hostname: clamav
    <<: *default-opts    
    volumes:
      - clamav_defs:/var/lib/clamav
    environment:
      << : *common-vars
    stop_grace_period: 1m
    deploy:
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 20
        window: 40s

  dovecot:
    image: neomediatech/dovecot-honey:latest
    hostname: dovecot-honey
    <<: *default-opts
    ports:
      - target: 143
        published: 10143
        protocol: tcp
        mode: host
      - target: 993
        published: 10993
        protocol: tcp
        mode: host
      - target: 110
        published: 10110
        protocol: tcp
        mode: host
      - target: 995
        published: 10995
        protocol: tcp
        mode: host
    volumes:
      - logs:/var/log/dovecot/
      - dovecot_good_data:/data/dovecot
    environment:
      << : *common-vars

  php-fpm:
    image: php:7.3-fpm-alpine
    hostname: php-fpm
    <<: *default-opts
    volumes:
      - web:/usr/share/nginx/html/
      - logs:/var/www/html/
    environment:
      << : *common-vars
    healthcheck:
      test: ["CMD", "nc", "-w", "7", "-zv", "0.0.0.0", "9000"]
      interval: 30s
      timeout: 30s
      start_period: 60s
      retries: 20

  opencanary:
    image: neomediatech/opencanary:latest
    hostname: opencanary
    <<: *default-opts    
    environment:
      << : *common-vars
      OPENCANARY_NODE_ID: "${OPENCANARY_NODE_ID:-opencanary}"
    stop_grace_period: 20s
    ports:
      - target: 21
        published: 2021
        protocol: tcp
        mode: host
      - target: 22
        published: 2022
        protocol: tcp
        mode: host
      - target: 23
        published: 2023
        protocol: tcp
        mode: host
      - target: 2323
        published: 2323
        protocol: tcp
        mode: host
      - target: 5900
        published: 25900
        protocol: tcp
        mode: host
      - target: 3306
        published: 23306
        protocol: tcp
        mode: host    
      - target: 6379
        published: 26379
        protocol: tcp
        mode: host    
      - target: 1433
        published: 21433
        protocol: tcp
        mode: host
      - target: 3389
        published: 23389
        protocol: tcp
        mode: host
      - target: 8080
        published: 18080
        protocol: tcp
        mode: host
      - target: 69
        published: 269
        protocol: udp
        mode: host
      - target: 161
        published: 2161
        protocol: udp
        mode: host
      - target: 123
        published: 2123
        protocol: udp
        mode: host
    volumes:
      - logs:/data

  samba:
    image: neomediatech/samba-honey:latest
    hostname: samba
    <<: *default-opts    
    environment:
      << : *common-vars
    ports:
      - target: 139
        published: 23139
        protocol: tcp
        mode: host
      - target: 445
        published: 23445
        protocol: tcp
        mode: host
    volumes:
      - logs:/var/log/samba
      - samba_shares:/shares

  roundcube:
    image: roundcube/roundcubemail
    hostname: roundcube
    <<: *default-opts    
    environment:
      << : *common-vars
      ROUNDCUBEMAIL_DEFAULT_HOST: dovecot-good
      ROUNDCUBEMAIL_SMTP_SERVER: nosmtp
    stop_grace_period: 20s
    ports:
      - target: 80
        published: 8880
        protocol: tcp
        mode: host
    volumes:
      - roundcube_data:/var/www/html/db/

  dovecot-good:
    image: neomediatech/dovecot:latest
    hostname: dovecot
    <<: *default-opts    
    ports:
      - target: 143
        published: 31143
        protocol: tcp
        mode: host
    volumes:
      - logs:/data/logs
      - dovecot_good_data:/data
      
volumes:
  redis_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/redis/db
  rspamd_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/rspamd/var
  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/nginx/html
  nginx_confs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/nginx/conf
  clamav_defs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/clamav/defs
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/logs
  dovecot_good_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/dovecot
  exim_good_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/dovecot/home/honeyuser/Maildir/
  roundcube_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/roundcube/db/
  samba_shares:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/honeypot/samba/shares/
