# stack name "intranet"
version: '3.7'

services:
  app:
    image: neomediatech/php:8.1-apache
    hostname: app
    ports:
      - target: 80
        published: 85
        protocol: tcp
        mode: host
    volumes:
      - app:/var/www/html
      - logs:/var/log/apache
      - /srv/data/intranet/1-custom.ini:/usr/local/etc/php/conf.d/1-custom.ini:ro
    environment:
      TZ: Europe/Rome
    depends_on:
      - db
    healthcheck:
      disable: true
    stop_grace_period: 20s

  db:
    image: mariadb:10.10
    hostname: db
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /var/lib/mysql/db-root.pwd
      MYSQL_PASSWORD_FILE: /var/lib/mysql/db-intranet.pwd
      MYSQL_DATABASE_FILE: /var/lib/mysql/db-name.txt
      MYSQL_USER_FILE: /var/lib/mysql/db-user.txt
      TZ: Europe/Rome
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "read p < $$MYSQL_PASSWORD_FILE ; read u < $$MYSQL_USER_FILE ; mysql -p$$p -u$$u -e status | grep Uptime || (echo \"MariaDB is down\" && exit 1)"]
      interval: 30s
      timeout: 30s
      start_period: 1s
      retries: 20
    stop_grace_period: 5s

volumes:
  common_data:
    driver: local
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/logs/intranet
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/databases/intranet
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/intranet/app
