# Add a new file /etc/rsyslog.d/10-docker-logs.conf
# provides UDP syslog reception
# module(load="imudp")
# input(type="imudp" port="514")
# provides TCP syslog reception
# module(load="imtcp")
# input(type="imtcp" port="514")
# $FileCreateMode 0644
# template(name="DockerLogFileName" type="list") {
#    constant(value="/var/log/docker-containers/")
#    property(name="syslogtag" securepath="replace" \
#             regex.expression="docker-\\(.*\\)\\[" regex.submatch="1")
#    constant(value="/docker.log")
# }
# if $syslogtag startswith 'docker-' then ?DockerLogFileName
# $FileCreateMode 0600
#
# then: systemctl restart rsyslog.service

version: '3.7'

services:
  logspout:
    image: gliderlabs/logspout
    hostname: logspout
    ports:
      - target: 80
        published: 18080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    networks:
      - logspout-net
    command:
      syslog://10.205.33.1:514

networks:
  logspout-net:
    name: logspout-net
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.205.33.0/24
