# stack name "pusher"
# nginx alpine default root : /usr/share/nginx/html
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      #max_attempts: 3
      window: 20s

services:
  redirector:
    image: nginx:1.18-alpine
#    restart: unless-stopped
    hostname: pusher
    <<: *default-opts    
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - pusher_confs:/etc/nginx/conf.d
      - /srv/data/redirector/ssl-dhparams.pem:/data/ssl-dhparams.pem:ro
      - certbot_certs:/data/certs
      - certbot_deals:/var/www/certbot
      - /srv/data/redirector/assets:/var/www/nil:ro
      - logs:/data/log
    environment:
      TZ: Europe/Rome
    depends_on:
      - certbot
    extra_hosts:
      - "dockerhost:172.16.217.15"
    command: "/bin/sh -c 'echo -n \"Waiting for certbot...\"; until ping certbot -c1 >/dev/null; do sleep 1; echo -n \"...\"; done; echo \"OK\"; while :; do sleep 22h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    healthcheck:
#      test: curl --fail -s http://localhost:5000/ || exit 1
#      interval: 1m30s
#      timeout: 10s
#      retries: 3

  certbot:
    image: certbot/certbot
    hostname: certbot
    <<: *default-opts    
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_deals:/var/www/certbot
      - certbot_var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 23h & wait $${!}; done;'"
    environment:
      TZ: Europe/Rome

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/logs/redirector
  pusher_confs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/redirector/confs
  certbot_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/certbot/conf
  certbot_deals:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/certbot/www
  certbot_var:
    driver: local
 
