# stack name "pusher"
# nginx alpine default root : /usr/share/nginx/html
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      #max_attempts: 3
      window: 20s

services:
  redirector:
    image: nginx:1.15-alpine
#    restart: unless-stopped
    hostname: pusher
    <<: *default-opts    
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - pusher_confs:/etc/nginx/conf.d
      - /srv/data/docker/docker-compose-projects/spiderweb-new/nginx/ssl-dhparams.pem:/data/ssl-dhparams.pem:ro
      - certbot_certs:/data/certs
      - certbot_deals:/var/www/certbot
      - /srv/data/docker/docker-compose-projects/spiderweb-new/nginx/404.html:/var/www/nil/404.html:ro
      - /srv/data/docker/docker-compose-projects/spiderweb-new/nginx/404.css:/var/www/nil/404.css:ro
    environment:
      TZ: Europe/Rome
    depends_on:
      - certbot
    command: "/bin/sh -c 'echo -n \"Waiting for website...\"; until ping app -c1 >/dev/null; do sleep 1; echo -n \"...\"; done; echo \"OK\"; echo -n \"Waiting for webmail...\"; until ping webmail -c1 >/dev/null; do sleep 1; echo -n \"...\"; done; echo \"OK\"; while :; do sleep 22h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    healthcheck:
#      test: curl --fail -s http://localhost:5000/ || exit 1
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
    external_links:
      - email:nginx
      - website:nginx
    networks:
      - default
      - email_default
      - website_default

  certbot:
    image: certbot/certbot
    hostname: certbot
    <<: *default-opts    
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_deals:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 23h & wait $${!}; done;'"
    environment:
      TZ: Europe/Rome

networks:
  email_default:
    external: true
  website_default:
    external: true

volumes:
  pusher_confs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/redirector/nginx_confs
  certbot_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/certbot/conf
  certbot_deals:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/certbot/www
