# use to create a swarm template in Portainer
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: any
      delay: 5s
      max_attempts: 3
      window: 30s

services:
  redis:
    image: redis:7-alpine
    environment:
      TZ: Europe/Rome
      VOL_PATH: "${VOL_PATH:-/srv/data/docker/containers/redis-no/db}"
      HOSTNAME: "${HOSTNAME:-redis-antispam-neo}"
      LISTEN: "${LISTEN:-6379}"
    hostname: ${HOSTNAME}
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no", "--always-show-logo", "no", "--appendfsync", "no"]
    <<: *default-opts    
    ports:
      - target: 6379
        published: ${LISTEN}
        protocol: tcp
        mode: host
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 10s
      retries: 10

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOL_PATH}
