# WARNING: This stack depends on traefik-v2.yml stack
# STACK_BASE_PATH [base folder where to host files, must exists]
# FQDN_HOST: FQDN to reach (and for LE certificate)

version: '3.7'

services:
  echoip:
    image: neomediatech/echoip
    hostname: echoip
    networks:
      - traefik-public
    command: ["-H", "X-Real-IP", "-r", "-c", "/data/city.mmdb","-f", "/data/country.mmdb","-a", "/data/asn.mmdb"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.echoip.entrypoints=https, http"
        - "traefik.http.routers.echoip.rule=Host(`${FQDN_HOST}`)"
        - "traefik.http.routers.echoip.service=echoip"
        - "traefik.http.routers.echoip.middlewares=rate-limit@file"
        - "traefik.http.services.echoip.loadbalancer.server.port=8080"
    volumes:
      - ${STACK_BASE_PATH}/:/data

networks:
  traefik-public:
    external: true
