# WARNING: !!! WIP !!!
# WARNING: This stack depends on traefik-v2.yml stack
# STACK_BASE_PATH [base folder where to host files, must exists]
# DOMAIN: base domain for LE certificates

version: '3.7'

services:
  nginx-catchall:
    image: nginx
    hostname: catch-all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/data/docker/containers/traefik/nginx/conf:/etc/nginx/conf.d:ro
      - /srv/data/docker/containers/traefik/nginx/html:/data/html:ro
      - traefik_logs:/data/logs
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
          #- "traefik.http.routers.nginx-catchall.rule=(Host(`${FQDN_HOST}`) || HostRegexp(`{any:.+}`))"
        - "traefik.http.routers.nginx-catchall.rule=Host(`${FQDN_HOST}`)"
        - "traefik.http.routers.nginx-catchall.entrypoints=https"
        - "traefik.http.services.nginx-catchall.loadbalancer.server.port=80"
        - "traefik.http.routers.nginx-catchall.service=nginx-catchall"
        - "traefik.http.routers.nginx-catchall.priority=1"

networks:
  traefik-public:
    external: true

volumes:    
  traefik_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/docker/containers/traefik/logs
