version: '3.2'

services:
  portainer:
    image: portainer/portainer
    command: -H "tcp://tasks.portainer_agent:9001" --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer_agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  agent:
    image: portainer/agent
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  edge_agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: "tasks.portainer_edge_agent"
      EDGE: "1"
      EDGE_ID: "your-edge-id"
      EDGE_KEY: "your-edge-key"
      CAP_HOST_MANAGEMENT: "1"
      EDGE_INSECURE_POLL: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_data:/data
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  portainer_agent:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/portainer/data
